name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: 'install build dependencies'
      run: |
        sudo apt-get update
        sudo apt-get install -y groff

    - name: 'compile resume'
      run: make
